name: Build and deploy artifacts to cloudsmith
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout protobuf files
        uses: actions/checkout@v4

      - name: Make protoc available
        uses: arduino/setup-protoc@v3
        with:
          version: "27.2"

      - name: Generate classes
        run: protoc --proto_path=./ --java_out=./generated/java/src/main/java --php_out=./generated/php/build/src ./protocols/**/*.proto

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Generate Java classes
        run: cd ./generated/java || exit && mvn clean package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: keepsake-protos
          path: ./generated/java/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Retrieve jar
        uses: actions/download-artifact@v3
        with:
          name: keepsake-protos
          path: .
      - name: Rename jar
        run: mv keepsake-proto-* keepsake-proto.jar
      - name: Push jar to cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          curl --request POST \
          --url https://api.cloudsmith.io/v1/packages/desertrat-io/keepsake/upload/maven/ \
          --header "X-Api-Key: ${CLOUDSMITH_API_KEY}" \
          --header 'accept: application/json' \
          --header 'content-type: application/json'
          --data '{"package_file": "./keepsake-proto.jar"}'
          
