name: Build and deploy artifacts to cloudsmith
on:
  pull_request:
    types:
      - closed

jobs:
  build:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout protobuf files
        uses: actions/checkout@v4

      - name: Make protoc available
        uses: arduino/setup-protoc@v3
        with:
          version: "25.3"

      - name: Generate classes
        run: protoc --proto_path=./ --java_out=./generated/java/src/main/java --php_out=./generated/php/build/src ./protocols/**/*.proto

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Generate Java classes
        run: cd ./generated/java || exit && mvn clean package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: keepsake-java-proto
          path: ./generated/java/target/*.jar
      - name: Upload pom
        uses: actions/upload-artifact@v3
        with:
          name: keepsake-proto-pom
          path: ./generated/java/pom.xml

      - name: Package PHP (don't need the php action because we're just zipping files)
        run: |
          cd generated/php/build
          zip -r keepsake-php-proto.zip src/ composer.json composer.lock
      - name: Now upload the php zip
        uses: actions/upload-artifact@v3
        with:
          name: keepsake-php-proto
          path: ./generated/php/build/keepsake-php-proto.zip
  deploy-jar:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Retrieve jar
        uses: actions/download-artifact@v3
        with:
          name: keepsake-java-proto
          path: .

      - name: Retrieve pom
        uses: actions/download-artifact@v3
        with:
          name: keepsake-proto-pom
          path: .
      - name: Rename jar
        run: |
          mv keepsake-proto-* keepsake-proto.jar
          ls -h
      - name: Push jar to cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "maven"
          owner: "desertrat-io"
          repo: "keepsake"
          file: "keepsake-proto.jar"
          republish: "false"
          pom-file: "pom.xml"
  deploy-composer:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Retrieve PHP archive
        uses: actions/download-artifact@v3
        with:
          name: keepsake-php-proto
          path: .
      - name: Upload and sync with cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "composer"
          owner: "desertrat-io"
          repo: "keepsake"
          file: "keepsake-php-proto.zip"